package org.refactorkit.core

/** Versioned defensive limits for local stdio protocol surfaces. */
object ProtocolLimits {
    const val MAX_REQUEST_BYTES = 1_048_576
    const val MAX_LSP_FRAME_BYTES = 1_048_576
    const val MAX_PENDING_PLANS = 128
    const val MAX_SYMBOL_RESULTS = 200
    const val MAX_WORKSPACE_INDEX_SOURCES = 100_000
    const val MAX_WORKSPACE_INDEX_SYMBOLS = 100_000
    const val MAX_WORKSPACE_INDEX_PROVIDER_SYMBOLS = 50_000
    const val MAX_INTELLIGENCE_QUERY_CHARS = 512
    const val MAX_REFERENCE_RESULTS = 1_000
    const val MAX_SOURCE_FILE_BYTES = 10_485_760
    const val MAX_PREVIEW_DIFF_BYTES = 524_288
    const val MAX_PREVIEW_DIFF_FILES = 128
    const val MAX_PREVIEW_HUNKS_PER_FILE = 64
    const val MAX_PREVIEW_LINES_PER_HUNK = 2_000
    const val MAX_PREVIEW_DIAGNOSTICS = 500
    const val MAX_PREVIEW_DIAGNOSTIC_BYTES = 262_144
    const val MAX_DIAGNOSTIC_MESSAGE_CHARS = 4_096
    const val MAX_DIAGNOSTICS_RESPONSE_BYTES = 2_097_152
    const val MAX_DIAGNOSTICS_REQUEST_ID_CHARS = 128
    const val MAX_DIAGNOSTICS_OVERLAY_DOCUMENTS = 128
    const val MAX_DIAGNOSTICS_OVERLAY_BYTES = 786_432
    const val MAX_DAEMON_STDERR_BYTES = 65_536
    const val MAX_BUILD_MODELS = 16
    const val MAX_BUILD_MODULES = 1_024
    const val MAX_BUILD_SOURCE_SETS_PER_MODULE = 64
    const val MAX_BUILD_ROOTS_PER_SOURCE_SET = 256
    const val MAX_BUILD_MODULE_DEPENDENCIES_PER_SOURCE_SET = 1_024
    const val MAX_BUILD_MODEL_DIAGNOSTICS = 500
    const val MAX_SEMANTIC_PROCESSES = 8
    const val MAX_SEMANTIC_PROCESS_ARGUMENTS = 128
    const val MAX_SEMANTIC_PROCESS_STDOUT_BYTES = 67_108_864L
    const val MAX_SEMANTIC_PROCESS_STDERR_BYTES = 65_536
    const val MAX_EXTERNAL_FILE_EDITS = 1_000
    const val MAX_EXTERNAL_TEXT_EDITS = 10_000
    const val MAX_EXTERNAL_REPLACEMENT_BYTES = 16_777_216L
    const val MAX_SEMANTIC_OVERLAY_FILES = 100_000
    const val MAX_SEMANTIC_OVERLAY_BYTES = 536_870_912L
}
